Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end

  config.vm.provision "file", source: "~/.ssh/other_keys/vms_key", destination: ".ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/other_keys/vms_key.pub", destination: ".ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

  config.vm.provision "shell", inline: <<-SHELL
    apt-add-repository ppa:opencontrail/ppa
    apt-get update
    apt-get install -y git cmake
    apt-get install -y autoconf automake bison debhelper flex libcurl4-openssl-dev libexpat-dev libgettextpo0 libprotobuf-dev libtool libxml2-utils make protobuf-compiler python-all python-dev python-lxml python-setuptools python-sphinx ruby-ronn scons unzip vim-common libsnmp-python libipfix-dev librdkafka-dev librdkafka1
    apt-get install -y libboost-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libcurl4-openssl-dev google-mock libgoogle-perftools-dev liblog4cplus-dev libtbb-dev libhttp-parser-dev libxml2-dev libicu-dev
    apt-get install -y libpcap-dev libnl-genl-3-dev libnl-3-dev libzookeeper-mt-dev libzookeeper-mt2
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    mkdir -p ~/bin
    curl -sS https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
  SHELL
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    mkdir -p ~/contrail-vrouter
    cd ~/contrail-vrouter && repo init -u git@github.com:codilime/contrail-vnc -m vrouter-manifest.xml -b windows && repo sync
    cd ~/contrail-vrouter/third_party && python fetch_packages.py
    mkdir -p ~/contrail-vrouter/third_party/cassandra
    cd ~/contrail-vrouter/third_party/cassandra && wget https://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver_2.2.0-1_amd64.deb && wget https://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver-dev_2.2.0-1_amd64.deb && wget https://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.7.5/libuv_1.7.5-1_amd64.deb && sudo dpkg -i libuv_1.7.5-1_amd64.deb cassandra-cpp-driver_2.2.0-1_amd64.deb cassandra-cpp-driver-dev_2.2.0-1_amd64.deb
  SHELL
end
